# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  pathtosolution: "P1-Zachary-Fisher/"
  buildConfiguration: 'Release'
  pathtotest: "P1-Zachary-Fisher/PizzaTest"

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud connection 1'
    organization: '$(SonarOrganization)'
    scannerMode: 'MSBuild'
    projectKey: '$(SonarProjectKey)'
    projectName: '$(SonarProjectName)'
    extraProperties: |
      sonar.cs.opencover.reportsPaths="$(Build.ArtifactStagingDirectory)/coverage/*"
      sonar.cs.vstest.reportsPaths="$(Build.ArtifactStagingDirectory)/test/*.trx"
      sonar.exclusions=**/wwwroot/lib/**/*


- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/PizzaTest/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput="$(Build.ArtifactStagingDirectory)/coverage/"
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet test'

- task: DotnetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(pathtotest)'
    workingDirectory: '$(pathtosolution)'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: --configuration $(buildConfiguration)
    publishWebProjects: true
    zipAfterPublish: true
    workingDirectory: '$(pathtosolution)'
  displayName: 'dotnet publish + zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(df043942-964a-402b-8121-92387a0265a3)'
    appType: 'webAppLinux'
    appName: 'PizzaBoxzf'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'