# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  pathtosolution: "P1-Zachary-Fisher/"
  buildConfiguration: 'Release'
  pathtotest: "P1-Zachary-Fisher/PizzaTest"

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test
    --configuration $(buildConfiguration)
    --logger trx
    --no-build
    --results-directory $(Build.ArtifactStagingDirectory)/PizzaTest/
    /p:CollectCoverage=true
  workingDirectory: $(pathtosolution)
  displayName: 'dotnet test'

- task: DotnetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(pathtotest)'
    workingDirectory: '$(pathtosolution)'